import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

import {NextAuthProvider, QueryClientProviderOverride, ThemeProvider} from "@/app/providers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" suppressHydrationWarning={true}>
        <body className={inter.className} suppressHydrationWarning={true}>

        <QueryClientProviderOverride>
            <NextAuthProvider>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>

            </NextAuthProvider>
        </QueryClientProviderOverride>


        </body>
        </html>
    );
}